local F, C = unpack(select(2, ...))

tinsert(C.themes["AuroraClassic"], function()
	AudioOptionsFrameHeader:SetAlpha(0)
	AudioOptionsFrameHeader:ClearAllPoints()
	AudioOptionsFrameHeader:SetPoint("TOP", AudioOptionsFrame, 0, 0)
	F.ReskinFrame(AudioOptionsFrame)
	F.ReskinButton(AudioOptionsFrameOkay)
	F.ReskinButton(AudioOptionsFrameCancel)
	F.ReskinButton(AudioOptionsFrameDefaults)
end)