local F, C = unpack(select(2, ...))

tinsert(C.themes["AuroraClassic"], function()
	ColorPickerFrameHeader:SetAlpha(0)
	ColorPickerFrameHeader:ClearAllPoints()
	ColorPickerFrameHeader:SetPoint("TOP")
	F.ReskinFrame(ColorPickerFrame, true)
	F.ReskinButton(ColorPickerOkayButton)
	F.ReskinButton(ColorPickerCancelButton)
	F.ReskinSlider(OpacitySliderFrame, true)
end)