local F, C = unpack(select(2, ...))

tinsert(C.themes["AuroraClassic"], function()
	F.ReskinFrame(ScrollOfResurrectionSelectionFrame)
	F.ReskinFrame(ScrollOfResurrectionFrame)

	ScrollOfResurrectionSelectionFrameBackground:Hide()
	F.ReskinScroll(ScrollOfResurrectionSelectionFrameListScrollFrameScrollBar)
	F.ReskinInput(ScrollOfResurrectionSelectionFrameTargetEditBox)
	F.ReskinInput(ScrollOfResurrectionFrameNoteFrame)
	F.ReskinButton(ScrollOfResurrectionSelectionFrameAcceptButton)
	F.ReskinButton(ScrollOfResurrectionSelectionFrameCancelButton)
	F.ReskinButton(ScrollOfResurrectionFrameAcceptButton)
	F.ReskinButton(ScrollOfResurrectionFrameCancelButton)
	F.CreateBDFrame(ScrollOfResurrectionSelectionFrameList, .25)
end)