local F, C = unpack(select(2, ...))

tinsert(C.themes["AuroraClassic"], function()
	F.CreateBD(ScrollOfResurrectionSelectionFrame)
	F.CreateSD(ScrollOfResurrectionSelectionFrame)
	F.CreateBD(ScrollOfResurrectionFrame)
	F.CreateSD(ScrollOfResurrectionFrame)

	ScrollOfResurrectionSelectionFrameBackground:Hide()
	F.StripTextures(ScrollOfResurrectionFrameNoteFrame, true)
	F.ReskinScroll(ScrollOfResurrectionSelectionFrameListScrollFrameScrollBar)
	F.ReskinInput(ScrollOfResurrectionSelectionFrameTargetEditBox)
	F.ReskinInput(ScrollOfResurrectionFrameNoteFrame)
	F.Reskin(ScrollOfResurrectionSelectionFrameAcceptButton)
	F.Reskin(ScrollOfResurrectionSelectionFrameCancelButton)
	F.Reskin(ScrollOfResurrectionFrameAcceptButton)
	F.Reskin(ScrollOfResurrectionFrameCancelButton)
	F.CreateBDFrame(ScrollOfResurrectionSelectionFrameList, .25)
end)