-- 重定义部分函数
GOLD_AMOUNT_SYMBOL = format("|cffffd700%s|r", GOLD_AMOUNT_SYMBOL)
SILVER_AMOUNT_SYMBOL = format("|cffd0d0d0%s|r", SILVER_AMOUNT_SYMBOL)
COPPER_AMOUNT_SYMBOL = format("|cffc77050%s|r", COPPER_AMOUNT_SYMBOL)

GOLD_AMOUNT = "%d"..GOLD_AMOUNT_SYMBOL
SILVER_AMOUNT = "%d"..SILVER_AMOUNT_SYMBOL
COPPER_AMOUNT = "%d"..COPPER_AMOUNT_SYMBOL