--- 重定义部分函数
BAG_ITEM_QUALITY_COLORS[0] = { r = 0.4, g = 0.4, b = 0.4 }
BAG_ITEM_QUALITY_COLORS[1] = { r = 0.9, g = 0.9, b = 0.9 }
BAG_ITEM_QUALITY_COLORS[LE_ITEM_QUALITY_POOR] = { r = 0.4, g = 0.4, b = 0.4 }
BAG_ITEM_QUALITY_COLORS[LE_ITEM_QUALITY_COMMON] = { r = 0.9, g = 0.9, b = 0.9 }

GOLD_AMOUNT_SYMBOL = format("|cffffd700%s|r", GOLD_AMOUNT_SYMBOL)
SILVER_AMOUNT_SYMBOL = format("|cffb0b0b0%s|r", SILVER_AMOUNT_SYMBOL)
COPPER_AMOUNT_SYMBOL = format("|cffc77050%s|r", COPPER_AMOUNT_SYMBOL)

GOLD_AMOUNT = "%d"..GOLD_AMOUNT_SYMBOL
SILVER_AMOUNT = "%d"..SILVER_AMOUNT_SYMBOL
COPPER_AMOUNT = "%d"..COPPER_AMOUNT_SYMBOL

NORMAL_QUEST_DISPLAY = gsub(NORMAL_QUEST_DISPLAY, "000000", "ffffff")
TRIVIAL_QUEST_DISPLAY = gsub(TRIVIAL_QUEST_DISPLAY, "000000", "ffffff")
IGNORED_QUEST_DISPLAY = gsub(IGNORED_QUEST_DISPLAY, "000000", "ffffff")